<?php
/*
 * Mc2WebLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace Mc2WebLib;

use Mc2WebLib\Controllers;

/**
 * Mc2WebLib client class
 */
class Mc2WebClient
{
    /**
     * Constructor with authentication and configuration parameters
     */
    public function __construct(
        $basicAuthUserName,
        $basicAuthPassword,
        $BASEURI
    ) {
        Configuration::$basicAuthUserName = $basicAuthUserName;
        Configuration::$basicAuthPassword = $basicAuthPassword;
        Configuration::$BASEURI = $BASEURI;
    }
 
    /**
     * Singleton access to API controller
     * @return Controllers\APIController The *Singleton* instance
     */
    public function getClient()
    {
        return Controllers\APIController::getInstance();
    }
}
